@startuml

package "Wake-on-Radio Development Kit (WoR DK)" #e6e6fa {
    package DUT #ff6a6a {
        [nRF52840]
        [Si4467]

        nRF52840 --> Si4467 : SPI

        RF - [Si4467]
    }

    () "Power\nDC 3.3 V" as Power
    Power - DUT

        [TMUX1112] as TMUX_UART
        [TMUX1112] as TMUX_SWD

    package "UART Interface" #20b2aa {
        [FT232]
        () USB as USB_FT232

        FT232 - USB_FT232
    }

    package "DAPLink-based Programmer" #98fb98 {
        [NXP LPC11U35FHI33/501] as LPC11U35
        () USB as USB_LPC11U35

        LPC11U35 - USB_LPC11U35
    }

    [UART Selection] as UART_SELECT
    [Interface Control Selection] as IF_SELECT

    FT232 --> IF_SELECT : DTR
    LPC11U35 --> IF_SELECT : DTR
    IF_SELECT --> TMUX_UART : enable/\ndisable
    IF_SELECT --> TMUX_SWD : enable/\ndisable

    FT232 --> UART_SELECT : UART
    LPC11U35 --> UART_SELECT : UART
    UART_SELECT --> TMUX_UART : UART
    TMUX_UART --> nRF52840 : UART

    LPC11U35 --> TMUX_SWD : SWD
    TMUX_SWD --> nRF52840 : SWD
}

@enduml
