@startuml

package PCBA #e6e6fa {
    package "Electrical Separation" as connection #c0ec8b {

        package DUT #ff6a6a {
            [nRF52840]
            [Si4467]

            nRF52840 --> Si4467 : SPI

            RF - [Si4467]
        }

        () "Power\nDC 3.3 V" as Power
        Power - DUT

    }

    package "UART Interface" #20b2aa {
        [FT232]
    }

    package rusty-probe #98fb98 {
        [Raspberry Pi\nRP2040] as RPI
    }

    package Controller #87ceeb {
        [nRF52840_controller] as "nRF52840"
        collections "TMUX1111\n(or similar)" as TMUX

        nRF52840_controller --> TMUX : I/O
    }

    () USB

    package "USB Hub" #ff82ab {
        [Terminus Tech\nFE1.1s] as USBHub
    }

    USB - "USB Hub"

    USBHub --> nRF52840_controller : USB
    USBHub --> RPI : USB
    USBHub --> FT232 : USB

    RPI --> nRF52840 : SWD
    FT232 --> nRF52840 : UART

    TMUX --> connection
}

@enduml
